base:
    project: MLOps

raw_data:
    data_src: data_source

load_data:
    num_classes: 2
    row_data: data_soure
    preprocessed_data: data/processed
    full_path: dlproject/data_source

train :
    split_ratio: 0.80

model:
    name: CNN
    trainable: False
    train_path: data/processed/train
    test_path: data/processed/test
    optimizer: adam   
    loss: categorical_crossentropy  
    metrics: ["accuracy"]
    epochs: 1
    image_size: [255,255]
    # batch_size:32
    sav_dir: models/trained.h5
 
img_augment:
    rescale: 0.00392156862745098
    shear_range: 0.2
    zoom_range: 0.2
    horizontal_flip: True
    vertical_flip: True
    rotation_range: 20
    batch_size: 32
    class_mode: 'categorical'

model_dir: models

mlflow_config:
    artiact_dir: artifacts
    experiment_name: mlops_cnn
    run_name: mlops
    registered_model_name: deep_learning_VGG19
    remote_server_uri: http://127.0.0.1:5000
    